### ISSUE TITLE
The error described in file 2345.md does not match to code 2345

### ISSUE THREAD

**Issue by forresst** [mattpocock/ts-error-translator#100]
If we look error 2345 in [tsErrorMessages.json](https://github.com/mattpocock/ts-error-translator/blob/main/packages/engine/src/tsErrorMessages.json#L1662), we have the following description: 

```json
"Argument of type '{0}' is not assignable to parameter of type '{1}'."
```

But in file [2345.md](https://github.com/mattpocock/ts-error-translator/blob/main/packages/engine/errors/2345.md), the description is:

```json
"Property '{0}' is missing in type '{1}'."
```

Which seems to be the error [2324](https://github.com/mattpocock/ts-error-translator/blob/main/packages/engine/src/tsErrorMessages.json#L1582)

**Comment by mattpocock** [comment]
Feel free to PR a fix!
