### ISSUE TITLE
Add credits somewhere on the page

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mattpocock/ts-error-translator#110]
At the very least, a link to this GitHub repository would be good to have. Otherwise how will people know to send you issues? 😄 

I'd also like to add a Twitter link to https://twitter.com/mattpocockuk/ for credit.

**Comment by cyntler** [comment]
@JoshuaKGoldberg Here are my changes included GitHub link: https://github.com/mattpocock/ts-error-translator/pull/95

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
