### ISSUE TITLE
2554 not working correctly

### ISSUE THREAD

**Issue by Bassadin** [mattpocock/ts-error-translator#121]
![image](https://user-images.githubusercontent.com/1810902/190359338-04562249-c936-4e00-820d-eb7642ac2d3c.png)

I'd love to help fix this problem with a PR. Where can I get started? I've found the [json file](https://github.com/mattpocock/ts-error-translator/blob/main/apps/vscode/src/bundleErrors.json#L149), but I don't know where to start.

**Comment by mattpocock** [comment]
Take a look at CONTRIBUTING.md

**Comment by Bassadin** [comment]
> Take a look at CONTRIBUTING.md

Duh, why didn't I think about that. Thanks for the blazingly fast reply. I'll translate it as soon as I've got the time :)
Feel free to assign this issue to me if you want and thanks for this great project :)

**Comment by mattpocock** [comment]
Thanks pal! I'll delete the issue (otherwise we'd need to create issues for all missing translations) and you can steam ahead.

**Comment by Bassadin** [comment]
Fair :D Thanks anyways!

**Comment by Bassadin** [comment]
Actually, this seems to work well in [the web GUI](https://ts-error-translator.vercel.app/?error=KIDwDgpgxgLhAmACAjIghgJwOYFcC2EAdjAM4A0iARjjIlgPa0AMAdEA), but not in the VS Code plugin (see my OP).
