### ISSUE TITLE
Repo has no formatting config (e.g: prettier)

### ISSUE THREAD

**Issue by eddyw** [mattpocock/ts-error-translator#21]
Hey 👋 

It looks like some files (e.g: `engine.test.ts`) were saved without formatting. In vscode - for instance - by default vscode formatter removes trailing spaces on save, so saving a file for me causes unrelated changes (removes trailing spaces and comma).

It'd be great if prettier (or any other auto-formatting tool) was set. This'd ensure there is a consistent code style regardless of code editor's default formatting.

**Comment by mattpocock** [comment]
Fixed on main, and added formatting on lint-staged

**Comment by eddyw** [comment]
@mattpocock would it be possible to have a `.prettierrc.js` config file?
In vscode, for example, the prettier extension reads this config and can be set to use prettier for vscode on-save instead of default formatter. I think it'd also use the repo "prettier" version instead of the one baked-in in vscode.

For some reason prettier formatting on-save is different for me `npm run format`.

**Comment by mattpocock** [comment]
Pretty sure it also reads from the package.json?

**Comment by eddyw** [comment]
My bad, `git pull` failed because conflicts so I was actually still on the previous commit 🙈 

@mattpocock just one last minor comment. Not to start a war 🤣 .. but have you considered using tabs instead of spaces? spaces are hard-coded and forced but tabs are accessible because your code editor can display tabs as X number of spaces that you prefer. For example, some of my team prefer to see their code in 2 spaces, others in 4, and others have GitHub set to display it in 8 (more readable on code reviews), with tabs this has solved the issue because the amount of spaces you see depends on the environment configuration (your GitHub settings for X spaces or your code editor preferred Y spaces).

I mean .. just a comment 😅

**Comment by mattpocock** [comment]
https://www.youtube.com/watch?v=r3BO6GP9NMY
