### ISSUE TITLE
Restart/reset the tips?

### ISSUE THREAD

**Issue by Marouan-El-Haddad** [mattpocock/ts-error-translator#235]
Is it possible to somehow reset all the hints on syntax, so I can start over and see everything again from the beginning? I don't think this is a real bug, but I can't see where to do this.

**Comment by mattpocock** [comment]
Yes! Go into your settings.json and remove all of the mentioned tips

**Comment by Marouan-El-Haddad** [comment]
Thanks a lot for the help! It worked! :)
