### ISSUE TITLE
Add the extension to open-vsx.org

### ISSUE THREAD

**Issue by shaal** [mattpocock/ts-error-translator#36]
When using VScode online, in a service like https://gitpod.io (Dev environment in the cloud), you cannot access Microsoft's VSCode extensions marketplace.

There's an open-source alternative for that - https://open-vsx.org/about

Would you be willing to publish your wonderful extension there, so more people can use it?

Instructions here -
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Please let me know if you have any questions.

**Comment by mattpocock** [comment]
Done!

https://open-vsx.org/extension/mattpocock/ts-error-translator

**Comment by shaal** [comment]
Thank you! It works!

**Comment by janpio** [comment]
It seems OpenVSX is out of date with the main marketplace now, having 0.9.2 vs. 0.10.0. M
istake or intentional?

**Comment by ryonwasis311** [comment]
U are very clever .
