### ISSUE TITLE
The VSCode extension does not work in file without extension with language set to Typescript

### ISSUE THREAD

**Issue by paoloricciuti** [mattpocock/ts-error-translator#39]
I was opening an issue about the extension not working but i've luckly decided to testing in some file other than quokka scratchpad.

While the app seems to work ok in every ts file if you create a new file and select the language in VSCode setting it to typescript the typescript will check for typing errors but the extension will not translate.

![image](https://user-images.githubusercontent.com/26281609/166336535-1fe15412-363c-4ff3-87c8-47988764142b.png)

This is my VSCode version

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by mattpocock** [comment]
Fixed on main, releasing soon.
