### ISSUE TITLE
Bug 🐛: VSC extension isn't supported on vscode.dev (web)

### ISSUE THREAD

**Issue by YassinEldeeb** [mattpocock/ts-error-translator#43]
## Problem

As said [here](https://github.com/mattpocock/ts-error-translator/issues/15#issuecomment-1112573625) you care about web support, I think [this line](https://github.com/mattpocock/ts-error-translator/blob/6370c567d49335d3e060bfa85927630ed35bacc2/apps/vscode/src/humaniseDiagnostic.ts#L7) also uses the filesystem under the hood to read the JSON file from disk and parse it, so that's probably the reason why It's not supported for the web.

![image](https://user-images.githubusercontent.com/72823042/166458583-8da4e866-770c-44da-a9f3-07bc650df87b.png)

Personally, I can't see any incompatibility issues other than using the filesystem from reading the [why VSC extensions might not be supported on the web](https://code.visualstudio.com/docs/editor/vscode-web#_extensions), but you know better than me(cause you wrote it), can you notice any other incompatibility issues?

## Recommended solution
Instead of writing [`bundleErrors.json`](https://github.com/mattpocock/ts-error-translator/blob/main/apps/vscode/src/bundleErrors.json) to disk then reading it using the filesystem and parsing it, why not just write a JS file (ex: bundleErrors.js) containing the parsed object and read it as a JS file like this `import * as bundleErrors from './bundleErrors.js';`, so that It acts like if It was written inline as part of the source code, brilliant right?

**Comment by mattpocock** [comment]
@YassinEldeeb The reason it isn't supported is because we haven't set it up yet, not because of the JSON file.

**Comment by YassinEldeeb** [comment]
And how do you set it up? strange.

**Comment by mattpocock** [comment]
```
Extensions that have only a main entry point, but no browser are not web extensions. They are ignored by the web extension host and not available for download in the Extensions view.
```

I just to add `browser` to `package.json`.

**Comment by YassinEldeeb** [comment]
Silly me 😅, let's just keep this issue open if the JSON file was also a problem after adding `browser` to `package.json`

**Comment by mattpocock** [comment]
We can re-open if it's still a problem after I deploy.

**Comment by mattpocock** [comment]
Looks good!

**Comment by YassinEldeeb** [comment]
idk, what's wrong with me, I've an unhealthy obsession with that json file 😂😂
