### ISSUE TITLE
Translate quick fixes

### ISSUE THREAD

**Issue by Milo123459** [mattpocock/ts-error-translator#81]
VSCode provides quick fixes, it would be cool to see if this extension could translate the quick fixes so you know what it did to fix the error.

**Comment by mattpocock** [comment]
Are these particularly difficult to read? I don't see a use case here.

**Comment by Milo123459** [comment]
I'm recommending this extension a lot to beginners because it is especially helpful for them getting started. Just something that explains *how* it fixes the error so that this knowledge can be applied later.

**Comment by mattpocock** [comment]
Could you give an example?

**Comment by Milo123459** [comment]
<img width="205" alt="image" src="https://user-images.githubusercontent.com/50248166/167251756-cc0c94c0-f1b1-4394-819e-52d15d7aa9a3.png">

This would say this quick fix generates a blank function, or something like that.

**Comment by mattpocock** [comment]
Right, I think because you can just try the quick fix, you can see immediately what it does. That makes the 'translation' story less compelling.
