### ISSUE TITLE
less whitespace in vs code extension

### ISSUE THREAD

**Issue by KraXen72** [mattpocock/ts-error-translator#82]
currently, the hover popup in vs code has a lot of extra whitespace covering other code:
![image](https://user-images.githubusercontent.com/21956756/167309531-3c1eea80-5f51-4f4c-81ce-1a1296ec7a39.png)
  
what i'm suggesting that the TLDR should be on one/two lines:  
![edited](https://user-images.githubusercontent.com/21956756/167311283-383a08ff-874d-4439-bda2-8cfae2e3cf2c.png)
  
basically just use less space for the tldr. we're not talking about how long that mockup took me 😓

**Comment by mattpocock** [comment]
This is also when you have the 'show body text' config setting on too, right?

**Comment by KraXen72** [comment]
i mean, i would still want both, but preferrably the full translation wouldn't open the external translation site.
![image](https://user-images.githubusercontent.com/21956756/167557640-8a500bed-868d-47ab-8cdc-b8378968fe78.png)
this amount of text is ok by me, but would be good if i could still scroll/click to see the full translation right in the editor.

basically just put the "tldr" text and tldr translation on the same line and keep only 1 separator line between tldr and full translation
